### ISSUE TITLE
objects near to the camera look blurry

### ISSUE THREAD

**Issue by goutamyg** [amrgomaaelhady/SynthoGestures#2]
Hi,

Upon saving the uncompressed frames using ```Sequencer```, I see that the objects near the camera (highlighted in red) look blurry compared to the face of the mannequin. 
![image](https://github.com/amrgomaaelhady/SynthoGestures/assets/15650213/ec03ac69-baa1-4dcb-bed5-06beae2700f3)

I tried following things:
(i) Disabled motion blur in the Project Settings
(ii) Varied ```Depth of Field``` parameters under ```GlobalPostProcessingVolume```
(iii) Varied the RGB camera's Lens and Focus Settings under ```CineCameraActor34```

but the blurring of nearby objects persists. Can you suggest how to fix this issue?

**Comment by amrgomaaelhady** [comment]
Hi, as mentioned in the paper, the RGB is the default camera by Unreal Engine, and unfortunately, I have no control over how it is modeled. However, I can suggest the following solution, you could simply move the position of the camera backward as if it is inside the engine to get the correct focus (The camera position can be easily found in the settings or use the configuration .json file), and disable/hide the car interior to remove occlusion. You could also model your own camera behavior as we did with the depth and infrared cameras, but that is a lengthy process.

That being said, for realistic gestures, I wouldn't recommend using the RGB camera without modeling a more human-like hand. That is why we are using the depth camera in the paper, as it won't differ much between a human-like and a robot-like hands.

**Comment by goutamyg** [comment]
ok, thank you for your reply. Changing the location of camera (i.e., placing it backward) seem to not completely solve the problem. I checked the ```CameraType``` RGB and it does not have any operation causing the blur. 
![Screenshot 2024-06-21 121057](https://github.com/amrgomaaelhady/SynthoGestures/assets/15650213/475b3bb2-b955-4fdc-88a5-a8d6293dbdd4)

The issue seems to be due to [Depth-of-Field](https://docs.unrealengine.com/4.27/en-US/RenderingAndGraphics/PostProcessEffects/DepthOfField/) being applied somewhere in the framework, which I need to find. Thank you again for your kind reply. 

I have a question regarding the camera location: There are three places that define the camera location coordinates (i) camera.json, (ii) ```SettingsActor```, and (iii) the location of ```CineCameraActor34```. The coordinates in the json file and  ```SettingsActor``` match with each other, but not sure what exactly is the purpose of ```CineCameraActor34``` (as well as ```CineCameraActor2``` up in the sky). Can you please clarify?

**Comment by amrgomaaelhady** [comment]
Thank you for checking that out and sorry that I couldn't be of much help regarding the RGB Camera. You are definitely right with the depth of field, but I don't have much knowledge about it, however, it seems that you can still reduce this blurriness with both camera position and lights position. Maybe make sure you are positioning the correct camera. You can manipulate the position of existing lights as in the attached screenshot, or add more light sources.
![image](https://github.com/amrgomaaelhady/SynthoGestures/assets/33093924/0eb87d15-99ca-46fd-8ec8-b31d0adcacde)

When doing so and pulling the camera a bit back (and disabling the car object during gameplay), I got something like this, which is a bit better.

![image](https://github.com/amrgomaaelhady/SynthoGestures/assets/33093924/b0a3e125-da4e-4e63-88a2-a69d2a455510)

And, you are perfectly right that the camera.json and the ```SettingsActor``` are the only parts that control the cameras. Both ```CineCameraActor34``` and ```CineCameraActor2``` are old assets from previous attempts that are no longer used, you might as well delete them completely as I just did and nothing will be affected (although they are still connecting to other game objects, so you will get a warning upon deletion).

**Comment by goutamyg** [comment]
With the camera pulled backwards, the gesturing gets less blurry; but a blurry/hazy effect is visible as the hand approaches the camera ![0086](https://github.com/amrgomaaelhady/SynthoGestures/assets/15650213/9650bb2d-63bc-4538-bef1-80450a9e030c)
I am trying to run these RGB images through some monocular depth estimation methods and hence, any distortion in the RGB space affects the predicted depth. Thank you for your time helping me through the issue. If possible, kindly share the [x, y, z] camera coordinates used for the image you shared above.

**Comment by amrgomaaelhady** [comment]
Sure, it it possible, however, this was some random movement to check if it works. The coordinates are (X=229.484085,Y=-67.092163,Z=211.402145). Note that I have also moved the light sources:

![image](https://github.com/amrgomaaelhady/SynthoGestures/assets/33093924/bb0a9c46-2db5-4dfd-96ae-3cc246e42fea)

![image](https://github.com/amrgomaaelhady/SynthoGestures/assets/33093924/60f00381-19fa-449a-b5d4-77bca952ca67)
